# Generated by Django 5.1.1 on 2024-10-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='receipe_desctiption',
            new_name='receipe_description',
        ),
    ]
